/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TungiOutreachRouteImport } from './routes/tungi-outreach'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as OtherProjectsRouteImport } from './routes/other-projects'
import { Route as MontessoriProjectRouteImport } from './routes/montessori-project'
import { Route as IndexRouteImport } from './routes/index'

const TungiOutreachRoute = TungiOutreachRouteImport.update({
  id: '/tungi-outreach',
  path: '/tungi-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const OtherProjectsRoute = OtherProjectsRouteImport.update({
  id: '/other-projects',
  path: '/other-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MontessoriProjectRoute = MontessoriProjectRouteImport.update({
  id: '/montessori-project',
  path: '/montessori-project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/montessori-project': typeof MontessoriProjectRoute
  '/other-projects': typeof OtherProjectsRoute
  '/our-team': typeof OurTeamRoute
  '/tungi-outreach': typeof TungiOutreachRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/montessori-project': typeof MontessoriProjectRoute
  '/other-projects': typeof OtherProjectsRoute
  '/our-team': typeof OurTeamRoute
  '/tungi-outreach': typeof TungiOutreachRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/montessori-project': typeof MontessoriProjectRoute
  '/other-projects': typeof OtherProjectsRoute
  '/our-team': typeof OurTeamRoute
  '/tungi-outreach': typeof TungiOutreachRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/montessori-project'
    | '/other-projects'
    | '/our-team'
    | '/tungi-outreach'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/montessori-project'
    | '/other-projects'
    | '/our-team'
    | '/tungi-outreach'
  id:
    | '__root__'
    | '/'
    | '/montessori-project'
    | '/other-projects'
    | '/our-team'
    | '/tungi-outreach'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MontessoriProjectRoute: typeof MontessoriProjectRoute
  OtherProjectsRoute: typeof OtherProjectsRoute
  OurTeamRoute: typeof OurTeamRoute
  TungiOutreachRoute: typeof TungiOutreachRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tungi-outreach': {
      id: '/tungi-outreach'
      path: '/tungi-outreach'
      fullPath: '/tungi-outreach'
      preLoaderRoute: typeof TungiOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/other-projects': {
      id: '/other-projects'
      path: '/other-projects'
      fullPath: '/other-projects'
      preLoaderRoute: typeof OtherProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/montessori-project': {
      id: '/montessori-project'
      path: '/montessori-project'
      fullPath: '/montessori-project'
      preLoaderRoute: typeof MontessoriProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MontessoriProjectRoute: MontessoriProjectRoute,
  OtherProjectsRoute: OtherProjectsRoute,
  OurTeamRoute: OurTeamRoute,
  TungiOutreachRoute: TungiOutreachRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
